### ISSUE TITLE
Valuemapping

### ISSUE THREAD

**Issue by steevivo** [MogiePete/zabbix-galera-template#5] opened 2019-06-21 10:43 UTC
Hi,

Can tell me more where I push the valuemapping.txt file in zabbix ?

Thx

**Comment by MogiePete** [comment] 2019-09-28 15:44
Duplicate of #1 
[8 Value mapping](https://www.zabbix.com/documentation/4.0/manual/config/items/mapping)

**Closed as completed by MogiePete** 2019-09-28 15:44 UTC
